name: gsc
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^2.30.0  # Core Firebase SDK
  firebase_auth: ^4.17.5   # Firebase Authentication
  google_sign_in: ^6.2.1   # Google Sign-In SDK
  cloud_firestore: ^4.15.5 # Firestore (if you're storing user details)
  firebase_analytics: ^10.10.5 # Google Analytics for Firebase
  google_generative_ai: ^0.4.6
  flutter_gemini: ^3.0.0
  image_picker: ^1.1.2
  dash_chat_2: ^0.0.21

dev_dependencies:
  flutter_native_splash: ^2.3.3
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png  # Ensure this file is inside the assets folder

flutter_native_splash:
  color: "#000000"
  image: assets/logo.png
  android: true
  ios: true
  web: true
  fullscreen: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/logo.png"